redis:
  image: redis
db:
  image: postgres
  ports:
    "5432:5432"
  volumes:
    - ./docker/postgresql:/var/lib/postgresql
memcached:
  image: memcached
firebase:
  image: buddyup/firebase-server:latest
  ports:
   - "5000:5000"
api:
  image: buddyup/api:latest
   - "8100-8120:8100-8120"
   - "8400-8410:8400-8410"
  env_file: .env
  volumes:
    - ./app:/code/app
  command: bash -c 'service nginx start; gulp dev'
  links:
   - redis
   - db
   - memcached
   - firebase